const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');const h=__dirname,e=h+'/evidence',root=path.dirname(h),status=root+'/STATUS.md';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const event=(tag,msg)=>cp.execFileSync('/code/llm-settings/shared/skills/worker-protocol/scripts/status-event',[status,tag,msg]);
const frozen=JSON.parse(fs.readFileSync(e+'/report-freeze.json'));if(hash(fs.readFileSync(frozen.report))!==frozen.sha256)throw Error('report changed after freeze');
if(fs.readdirSync(root+'/inbox').length)throw Error('unread inbox before terminal');
const du=p=>Number(cp.execFileSync('du',['-s','-B1',p],{encoding:'utf8'}).split(/\s+/)[0]);
const logical=p=>Number(cp.execFileSync('du',['-sb',p],{encoding:'utf8'}).split(/\s+/)[0]);
const build=h+'/build';if(fs.lstatSync(build).isSymbolicLink()||fs.realpathSync(build)!==build)throw Error('retirement fence');
const before={allocated:du(build),logical:logical(build),hostFree:fs.statfsSync(h).bavail*fs.statfsSync(h).bsize};
fs.rmSync(build,{recursive:true});
const retirement={path:build,allocatedBytesRemoved:before.allocated,logicalBytesRemoved:before.logical,hostFreeBefore:before.hostFree,hostFreeAfter:fs.statfsSync(h).bavail*fs.statfsSync(h).bsize,timestamp:new Date().toISOString(),reportHash:frozen.sha256,note:'Only owned reproducible build tree removed. Source/logs/receipts/databases kept; host-free delta not attributed to this process.'};
fs.writeFileSync(e+'/build-retirement.json',JSON.stringify(retirement,null,2)+'\n');
event('BUILD-TREES-RETIRED',`path=${build} allocated_bytes_removed=${before.allocated} logical_bytes_removed=${before.logical} host_free_delta_not_attributed=true AUDIT-S28R2`);
fs.copyFileSync(status,e+'/STATUS-before-terminal.txt');
const exclude=new Set(['EVIDENCE-INVENTORY','EVIDENCE-INVENTORY.md','EVIDENCE-INVENTORY.json','ARTIFACT-HASHES.json']);const entries=[];
function walk(dir){for(const f of fs.readdirSync(dir).sort()){const p=path.join(dir,f),relative=path.relative(h,p);if(exclude.has(relative))continue;const st=fs.lstatSync(p);if(st.isSymbolicLink())entries.push({path:relative,type:'symlink',target:fs.readlinkSync(p)});else if(st.isDirectory())walk(p);else if(st.isFile())entries.push({path:relative,type:'file',bytes:st.size,sha256:hash(fs.readFileSync(p))});else throw Error('unexpected special file '+p);}}
walk(h);
const inventory={candidate:'ab25cd11b554bcd5ba64ca56a050c2eb21432d3c',root:h,reportSha256:frozen.sha256,builds:11,targeted:22,entries};
fs.writeFileSync(h+'/EVIDENCE-INVENTORY.json',JSON.stringify(inventory,null,2)+'\n');
let md='# Evidence inventory — S28-R2 FINAL\n\nAll paths are relative to this handoffs directory. JSON records complete\nfile identities without following symlinks. Compiled binaries were hashed\nbefore retirement; source, complete logs, diffs, receipts, authority copies\nand temporary runtime evidence remain. Inventory/hash manifests exclude\nthemselves to avoid circular hashes; terminal STATUS binds their identities.\n\n';
md+='| Artifact | Bytes | SHA256 |\n|---|---:|---|\n';
for(const r of entries)md+=`| [${r.path}](${r.path}) | ${r.bytes??0} | ${r.sha256??'link: '+r.target} |\n`;
fs.writeFileSync(h+'/EVIDENCE-INVENTORY.md',md);fs.writeFileSync(h+'/EVIDENCE-INVENTORY',md);
const names=['AUDIT-REPORT.md','REQUIREMENT-LEDGER.md','VERIFICATION-RECEIPTS.md','EVIDENCE-INVENTORY.json','EVIDENCE-INVENTORY.md'];
const hashes=names.map(p=>({path:h+'/'+p,sha256:hash(fs.readFileSync(h+'/'+p))}));fs.writeFileSync(h+'/ARTIFACT-HASHES.json',JSON.stringify(hashes,null,2)+'\n');
for(const r of entries)if(r.type==='file'&&hash(fs.readFileSync(h+'/'+r.path))!==r.sha256)throw Error('inventory verification failure '+r.path);
const git=(...a)=>cp.execFileSync('git',a,{encoding:'utf8'}).trim();
if(git('status','--porcelain')!==''||git('rev-parse','HEAD')!==inventory.candidate||hash(fs.readFileSync('gate.sh'))!=='c00b88a29989b11d09696d7afa164f7d9f93b59aee661a1b88a120c7a4934b75')throw Error('final candidate drift');
const retained=du(root),worktree=du('/code/kelgroups-audit-ab25cd1');
event('EVIDENCE-RETAINED',`root=${root} allocated_bytes=${retained} inventory=${h}/EVIDENCE-INVENTORY.json sha256=${hashes.find(r=>r.path.endsWith('EVIDENCE-INVENTORY.json')).sha256} files_verified=${entries.filter(r=>r.type==='file').length} AUDIT-S28R2`);
event('AUDIT-WORKTREE-RETIRABLE',`path=/code/kelgroups-audit-ab25cd1 allocated_bytes=${worktree} candidate=${inventory.candidate} retained-for-ticket-owner=true AUDIT-S28R2`);
event('MUTATION-CAMPAIGN',`state=closed stopped=set-point rows=6 killed=6 residual=0 blocked=0 open=0 builds=11/12 targeted=22/24 ledger=${h}/REQUIREMENT-LEDGER.md AUDIT-S28R2`);
event('AUDIT-RESULT',`verdict=AUDIT-PASS candidate=${inventory.candidate} tree=e52114c1f7a676073303ff76caa8f22821e0b2a3 report=${h}/AUDIT-REPORT.md sha256=${frozen.sha256} ledger_sha256=${hashes.find(r=>r.path.endsWith('REQUIREMENT-LEDGER.md')).sha256} builds=11/12 targeted=22/24 blocking=0 scope=FULL-local acceptance=ticket-owner marker=AUDIT-S28R2`);
event('COMPLETE',`AUDIT-S28R2 verdict=AUDIT-PASS worker=commit-auditor-s28r2 report=${h}/AUDIT-REPORT.md sha256=${frozen.sha256} builds=11/12 targeted=22/24 mandatory-floor-complete=true final-checkout-clean=true no-auto-retry-or-raise=true`);
console.log(JSON.stringify({hashes,filesVerified:entries.length,retirement,retainedBytes:retained,worktreeBytes:worktree},null,2));
