const fs=require('fs');const map=fs.readFileSync('admitted/submission-3/OPMAP-v9-requirement-verdict-grounds.txt','utf8').trim().split('\n').map((l,i)=>({row:i+1,c:l.split('|')}));const src=JSON.parse(fs.readFileSync('admitted/original-audit/source-compiled-map.json'));const notes={};function put(ids,status,note){for(const id of ids.split(',').flatMap(s=>{let [a,b]=s.split('-').map(Number);return b?Array.from({length:b-a+1},(_,i)=>a+i):[a]})){if(notes[id])throw Error('duplicate '+id);notes[id]={status,note}}}
put('1','SUPPORTED-STATIC','Grant: permitted=false collection, admin signer; keeping col contradicts permitted=true output. No executed kill.');
put('2','CHALLENGED','Ten fund-changing interpretations are semantically plausible, but OP13 is ambiguous. Donate OP22 preserves both conservation and its actual direct-unfold proof (guard value is unused), not PROOF-FAIL. Grant/accept consumers do not automatically fail after an earlier same-module error. See S-03.');
put('3','CHALLENGED','AUTH remains true. Actual proof calls eight inversion lemmas; six arms unfold step directly (open/deposit/withdraw/transfer/donate/backdonate). Claimed fourteen consumed upstreams is false; no automatic cascade.');
put('4','DEPENDENCY-ONLY','Consumes step_pledge_inv. Statement also becomes false with v=1 and omitted debit; dependency alone does not locate a downstream diagnostic.');
put('5-6','DEPENDENCY-ONLY','Consumes step_pledge_inv. Conti debit omission preserves uniqueness and duplicate refusal; no semantic kill or automatic consumer diagnostic.');
put('7','SUPPORTED-STATIC','Positive funded pledge with fresh user and collection contradicts debit equation when debit omitted.');
put('8','CONDITIONAL','Exact post-state differs if accepted transfer omitted; freeze whether pending removal remains. That distinction changes conservation row 2.');
put('9','SUPPORTED-STATIC','Pending pledge amount 1, correct admin/referee: omitting refund violates post-state equation.');
put('10','SUPPORTED-STATIC','Accepted amount 2 corrected to 1 with sufficient balance; omitted balance difference violates post-state equation.');
put('11','CHALLENGED','Consumes step_close_inv and close_guard_inv; permission statement survives spending omission. MUT site128 is a guard, unlike same OP16 spending atom131.');
put('12','DEPENDENCY-ONLY','Consumes step_close_inv; statement itself false for nonzero accepted total when cassa spending omitted. No observed downstream diagnostic.');
put('13','SUPPORTED-STATIC','Permitted nonempty accepted collection, no pending: omitted cassa spend contradicts stated result.');
put('14','SUPPORTED-STATIC','Nonzero refundable accepted pledge on fail; retained collection removal without refund contradicts result equation.');
put('15','SUPPORTED-STATIC','Admin opens fresh id; omitting new collection contradicts cons output.');
put('16-17','SUPPORTED-STATIC','Admin distinct from member, deposit1: missing conti credit contradicts double-entry/result equation.');
put('18-19','SUPPORTED-STATIC','Admin distinct from member, funded withdrawal1, non-stalled state: missing conti debit contradicts result/double-entry.');
put('20','SUPPORTED-STATIC','Two distinct admins transfer1: dropping outer signer credit changes cassa equation.');
put('21','SUPPORTED-STATIC','Admin donate0 admitted under constant-true positivity atom; original positive guard conjunct is false. Historical +1 mutant is different.');
put('22','CONDITIONAL','Omit member distribution while retaining comune debit; positive w and nonempty members contradict result. Precise retained debit must be frozen.');
put('23','SUPPORTED-STATIC','Deny collection carrying amount1: omission of refund while deleting escrow contradicts result equation.');
put('24','DEPENDENCY-ONLY','Reach induction consumes credit_pledges_step; comune-only credit omission preserves non-comune statement, not automatic failure.');
put('25','SUPPORTED-STATIC','Statement excludes comune; donate rw bal_bump_ne loses rewrite target. Proof-script sensitivity only, insufficient for semantic D2 obligation.');
put('26-28','DEPENDENCY-ONLY','Solvency consumers call named helper/carrier; comune credit omitted does not falsify member solvency. Same-module recovery must not be treated as obligatory cascading RED.');
put('29','CONDITIONAL','RefundAll->m falsifies conservation for escrow refund, but State.refundAll_sum fails in imported producer module first. Intended higher row needs separately bound observation path.');
put('30-31','SUPPORTED-STATIC','Fixed canonical view premise transport; actual boot/apply/admission producers exist. No production-absence conclusion.');
put('32','DEPENDENCY-ONLY','Carrier projection; opposite-side erase omission can falsify disjointness at a switching trace, but call does not establish this declaration emits RED.');
put('33','SUPPORTED-STATIC','Clean q with dissent[a], cast assent a: retaining dissent puts a in both tallies.');
put('34','SUPPORTED-STATIC','Tally inclusion remains true; assent-arm List.erase_subset no longer matches non-erased hypothesis. Proof-script sensitivity.');
put('35','CHALLENGED','sweepClosures_tallyKeys and consumed open/closed_mem/sweepStep_key do not depend on placeBallot. OP39 supplies no failing open_mem; attribution false.');
put('36','DEPENDENCY-ONLY','Uses effectedState_tally_growth/placeBallot_tally. Inclusion statement remains true under omitted erase; script/dependency distinction required.');
put('37-38','SUPPORTED-STATIC','Association-list/tally membership decomposition; no changed placeBallot call. Baseline structural classification only.');
put('39','DEPENDENCY-ONLY','Carrier opensOpen projection; OP40 can leave a closable q open, but projection is not independent observed kill.');
put('40','SUPPORTED-STATIC','closed projection unchanged by openQuestions filter change; proof uses only append/filterMap. Survivor prediction well supported.');
put('41-42','SUPPORTED-STATIC','Closable singleton under threshold0 is retained open; second sweep duplicates closure, and open_mem iff fails.');
put('43','DEPENDENCY-ONLY','Qids remain a superset; proof consumes open_mem, whose same-module failure does not itself imply this proof fails.');
put('44-45','DEPENDENCY-ONLY','OP40 creates open/closed overlap and stale open; semantic carrier failure distinct from assumed same-module cascade.');
put('46','SUPPORTED-STATIC','Idempotence of the explicitly written filter is a pure list equation; mutant changes production sweep call-site, not this statement.');
put('47','HISTORICAL-ONLY','Recovered standalone partition instrument; actual old dropSweep/fold and receipt differ from current production definition. No current kill.');
put('48','CHALLENGED','No mutant specified; named sweepStep_of_open dependency is real, but OP42 has no failing atom and cannot establish cascade.');
put('49-51','HISTORICAL-ONLY','Recovered badPlace/badEffect/own-fold instrument establishes its historical check result only; not three production theorem kills.');
put('52','HISTORICAL-ONLY','Recovered nostale instrument uses retired member events and own fold; no present row kill.');
put('53','HISTORICAL-ONLY','Recovered unfranchised recast instrument uses retired setRoles/admitMember; actual current franchise theorem remains required.');
put('54-55','HISTORICAL-ONLY','Bypass instrument compares its separately defined bypassApply result, not current universal noop theorem.');
put('56','HISTORICAL-ONLY','Recovered franchise instrument is not an independently observed current cast-noop failure.');
put('57','CONDITIONAL','An open arm returning a concrete closure falsifies none equality; close-branch lacks a complete record/precise diff.');
put('58','CONDITIONAL','wrong is no bound replacement term. Define a total qid-changing value (including a differing witness) before well-typed semantic prediction.');
put('59','SUPPORTED-STATIC','Congruence assumes pointwise threshold agreement and unfolds verdictOf; no threshold-value-dependent property claimed.');
put('60','DEPENDENCY-ONLY','Arbitrary event, prefix, hopen and semantic preservation premise; uses both WF lemmas. No mutant specified and no observation; original scope correction accepted.');
put('61','SUPPORTED-STATIC','Rejected premise drives simp; affected openQuestion has no error witness under bypass, other rejected arms remain.');
put('62','SUPPORTED-STATIC','Nonadmin opens fresh question in positive franchise view; bypass admits/effects it, falsifying identity.');
put('63','SUPPORTED-STATIC','Cast branch unchanged by openQuestion-only validation mutation.');
put('64-66','SUPPORTED-STATIC','Cast->gs preserves qids/SweepReady/tally inclusion; existing cast proof insists on assocInsert/placeBallot shape. Script sensitivity only.');
put('67','SUPPORTED-STATIC','Without sweep, effectedState still preserves qids; exact sweepClosures_preserves_qid term has changed target. Script sensitivity only.');
put('68','CHALLENGED','Without sweep, well-formedness is semantically false: empty WF state, admin opens collective q at threshold0; q remains open despite positive verdict. opensOpen fails.');
put('69-70','CHALLENGED','Fixed-initial fold preserves these properties semantically, but cons proof invokes ih at updated seed; tail mutant uses original seed. Exact terms are not definitionally equal. Literal accum->current is also not exact source text.');
put('71','CONDITIONAL','Changing foldVote alone to fixed empty seed breaks append at two fresh opens with threshold high; exact substitution still unfrozen. Distinct from OP52 foldFrom mutation.');
put('72-73','CONDITIONAL','Nonempty is not sufficient for failure: a unique clean open permission question can satisfy both carriers. Need concrete violating list; no unconditional THEOREM-FAIL.');
put('74','DEPENDENCY-ONLY','Admin projection consumes validateDirectAdmission_ok; nonadmin fresh-target witness falsifies statement under OP54 but does not prove consumer diagnostic.');
put('75-77','SUPPORTED-STATIC','OP54 permits nonadmin fresh nonreserved target under accepting hook; admin conjunct/refusal fails.');
put('78','CHALLENGED','No mutated atom; cites foldFrom_preserves_wellFormed while OP52 claims survivor. Original foldVote differs from mutated foldFrom, so exact carrier term may mismatch, not inherited observed RED.');
put('79','DEPENDENCY-ONLY','Under OP55 reserved-target conjunct false, but direct_admission_requires_admin admin conjunct still true. Consumer dependency not semantic failure.');
put('80-81','SUPPORTED-STATIC','Reserved fresh target can be admitted in generic integration with accepting hook, falsifying key!=reserved. Production apply may separately reject it.');
put('82','SUPPORTED-STATIC','Hook returns changed payload, mutation retains pre.appFold: hook/output equation false.');
put('83','SUPPORTED-STATIC','Pre/post members differ, hook succeeds: returning pre members falsifies post-member projection.');
put('84-85','SUPPORTED-STATIC','Threshold strengthening changes when hook runs, not absence or hook-on-reported-change; split proofs do not consume >= type.');
put('86','SUPPORTED-STATIC','Admitted app with nonempty members and successful fold; wiping members falsifies preservation.');
put('87','SUPPORTED-STATIC','No-op removal preserves absence; existing assocLookup_erase_of_none exact term mentions erased list. Script sensitivity.');
put('88','CONDITIONAL','Setting app change to concrete some value falsifies none equation; map some(admit) still needs exact payload. Measurement sidecar supplies a separate concrete sample.');
put('89-90','SUPPORTED-STATIC','Exactly two phantom KelGroups namespace rows withdrawn; actual Reactivegas declarations retained at rows97/98.');
put('91','SUPPORTED-STATIC','Removal identity preserves WF; current proof uses assocErase_keys_nodup/property at target fields. Script sensitivity.');
put('92','CHALLENGED','Proof never splits removeMember or unfolds enact; it derives Enacts from propose/approve threshold metadata, retaining finishEnact symbolically. Statement and proof survive the remove-member no-op.');
put('93','SUPPORTED-STATIC','Retaining pending proposal preserves existing WF; proof builds pendingKeys via erase lemma, so term shape mismatches.');
put('94','DEPENDENCY-ONLY','Consumes threshold lemma; > implies >=, so statement remains true, and call alone does not imply downstream RED.');
put('95-96','SUPPORTED-STATIC','Threshold statement remains true under stricter >; exact threshold has wrong relation and WF proof splits old >=. Script sensitivity, no semantic kill.');
put('97-98','SUPPORTED-STATIC','Pre franchise3/post2 with one assent: pre sweep leaves open, post sweep closes; projected vote equality can be false.');
put('99','SUPPORTED-STATIC','Existing same pending id, enough admins that new proposal does not enact; cons creates duplicate pending keys.');
put('100-101','SUPPORTED-STATIC','Existing signer approval, high majority so pending retained; cons duplicates approval. Lower-level theorem does not require validator admission.');
put('102','CHALLENGED','Root wrapper is real, but named OP60 counterpart row92 survives; no failing upstream supplied.');
put('103','DEPENDENCY-ONLY','Real root wrapper consumes KelGroups threshold theorem; retain distinct identity and conditional dependency, no observed kill.');
put('104-106','DEPENDENCY-ONLY','Actual WF/fold carrier consumers; may semantically fail under duplicate mutations, but declaration-specific diagnostics are unobserved.');
put('107-109','SUPPORTED-STATIC','Distinct root wrappers of structural WF projections; no new production kill.');
put('110','SUPPORTED-STATIC','Two admins satisfy positive even antecedent; mutated majority=3 gives 2*3<=2 false.');
put('111','SUPPORTED-STATIC','One-admin sample expects1, mutated majority yields2.');
put('112-113','CHALLENGED','Real wrapper counterparts, but text says OP67a kill (self operation); actual producer is OP67. Source call does not guarantee independent RED.');
put('114','CONDITIONAL','Any concrete duplicate key pair violates memberKeys Nodup; actual pair/type content must be frozen before execution.');
put('115','SUPPORTED-STATIC','Collection belonging to removed admin remains under keep-collections mutation; governanceEnacts false.');
put('116-119','SUPPORTED-STATIC','Explicit Bool conjunction projections; no production step invocation. Keep distinct required disposition, not mutation coverage.');
put('120-124,126-146','BASELINE-ONLY','Source is checkX=true by decide. Baseline shape correct; no implication of value-insensitivity. See checked 31 extents and current-atom counterexamples.');
put('125','BASELINE-ONLY','Actual declaration is Reactivegas.Step:470; decides boot/apply comune refusal and is value-sensitive under OP69L.');
put('147','CHALLENGED','Structural is right; boot elimination is not: solvent_init directly proves balances/collection facts of State.empty and has no boot premise.');
put('148','CONDITIONAL','Members wipe after successful production app falsifies equality on preservationDonate. Exact root edit/branch placement still not frozen.');
put('149','CHALLENGED','Shipped memberWritingApply check depends on preservationDonate/apply, not self-contained; OP69L rejects input and makes it false.');
put('150','CONDITIONAL','Distinct TraceTests proof-term mirror; same Bool can be false under OP69 but failed Step import prevents baseline wrapper loading. Not independent diagnostic.');
put('151-152','SUPPORTED-STATIC','Dropping productionWellFormed negation accepts comune boot and rejects mixed non-comune group: both decided claims become false.');
put('153','BASELINE-ONLY','all_checks_pass decides failing=[] from check table; no mutant allocated.');
put('154','BASELINE-ONLY','Real mutant-check mirror; OP69L false value path, Step import may fail.');
put('155-158','BASELINE-ONLY','Real RI proof-term mirror sites931/928/937/934; retain distinct identities and imported-module outcome.');
put('159-161','BASELINE-ONLY','Decide frozen check/inventory/corpus equalities; source baseline consistency, not production mutant evidence.');
put('162-163','BASELINE-ONLY','Actual sweep mirrors943/940; changes to fixture/production dependencies can falsify checks.');
put('164','BASELINE-ONLY','Trace stepDetailed/stepEvent erasure equation; generic wrapper shape, no current mutation receipt.');
put('165','BASELINE-ONLY','Composition appDecided exhaustive verdict disjunction from appVerdictAllows; structural cases.');
put('166','BASELINE-ONLY','Exact threshold consumer, not routing equation. Mutation changes upstream proof; no independent execution or auto-cascade.');
put('167','BASELINE-ONLY','Composition route cases characterize voteDerived/not-direct; source equation only.');
put('168','OPEN','ACCEPT is proposed operation label, not accepted result. Plain full-tree/default lake build does not bind final full mandate targets.');
put('169','BASELINE-ONLY','sweepDuplicating duplicates when filterMap nonempty; no claim about production sweep correctness follows.');
put('170','CHALLENGED','OPEN extent1 false: OP58B or OP69 wipes members on successful donate30; checkAppMembersPreservation=false, hence conjunction false.');
put('171','CHALLENGED','OPEN extent2 false: OP69L reverses input well-formedness; preservationDonate errors, memberWritingApply propagates, check=false.');
put('172','CONDITIONAL','OP63 and OP40 each flip fixture independently; plus must mean alternatives, not combined mutation. Same-module first-proof block claim unsupported.');
put('173','CONDITIONAL','OP67G leaves admin collection; OP57 retains pre payload; OP57B retains old members. Distinct alternatives need unique operation receipts. Same-module block not proved.');
put('174','SUPPORTED-STATIC','OP63 leaves pre-franchise sweep, differing from expected post-view sweep; source-site ordering cannot decide execution reachability.');
put('175','SUPPORTED-STATIC','OP23 distribution omission leaves alice/bob balances0 instead of1. Same-module :410 failure does not preclude later check elaboration.');
put('176','OPEN','Sanity uses comuneId and s62bThreshold=Vote.legacyThreshold. No listed current-map atom changes these values; pure/no-production overstates threshold dependency. Not inherently unfalsifiable or exempt.');
put('177','CONDITIONAL','Separate admin/reserved/duplicate mutations flip exact error checks. Under OP55 production post-WF rejects with different error, not necessarily admission.');
put('178','SUPPORTED-STATIC','Conjunction includes direct admission; its false value carries. No independently observed diagnostic.');
put('179-180','SUPPORTED-STATIC','OP49 admits bob openQuestion; explicit refusal/identity checks false. Failed Vote.Invariants import can block importing RI, distinct from same-module errors.');
put('181','CHALLENGED','OPEN extent12 false: OP58B wipes membership on first openQuestion, subsequent votes rejected, expected dissent absent. OP39-only survival is narrower than stated all-current-map claim.');
put('182','SUPPORTED-STATIC','OP58B member equality false on successful openQuestion; exact app output source inspected.');
put('183','CHALLENGED','OPEN extent14 false: OP50 cast->gs prevents alice and shipped bypass bob ballot placement; contains/equality conjunct false.');
put('184','CHALLENGED','OPEN extent15 false: OP69L rejects non-comune v3Group input; checkI57NoExpiry error branch false.');
put('185','CONDITIONAL','OP49 boundary or OP54 nonadmin-refusal conjunct can fail; alternatives must remain single-atom operations.');
put('186','SUPPORTED-STATIC','NoStale is V3BaseReachable && BaseRecomputeReachable; their OP63/40 flips inherit.');
put('187','SUPPORTED-STATIC','OP63 leaves q open/not closed; OP40 retains q both open and closed. Either falsifies partition fixture independently.');
put('188-189','SUPPORTED-STATIC','OP40 retains closed qp in open set at threshold1, falsifying isNone; policy mutant check includes same production assertion.');
put('190','OPEN','Current map retains stranger membership rejection/cast responsibility; no listed atom shown to affect these two refusal/identity assertions. Bounded unresolved relevance, not universal insensitivity.');
put('191','SUPPORTED-STATIC','Conjunction includes base recomputation so OP63 false value carries; same-file order not sufficient for execution block.');
put('192','CHALLENGED','OPEN extent23 false: OP58 stricter base threshold prevents Eve removal; v3PostView still3, required2, q one assent stays open. sweepDuplicating once==input, check=false.');
put('193','SUPPORTED-STATIC','OP40 retains q after enacted sweep; second sweep adds another closure so idempotence equation false.');
put('194','CHALLENGED','Distinct mirror of extent2; same OP69L false path. OPEN source pointer1084 is wrong (actual1090).');
put('195','CHALLENGED','Mirror refers line175 canonical economy, not its base-close producer172. Correct semantic atoms OP63/40; site931, not903.');
put('196','CHALLENGED','Mirror refers line172 base-close, not departure173. Correct alternatives OP67G/57/57B; site928, not901.');
put('197','CHALLENGED','Mirror refers line173 departure, not recompute174. Correct OP63; site937, not902.');
put('198','CHALLENGED','Mirror refers line174 recompute, not direct admission177. Correct OP54/55/56; site934, not897.');
put('199','CHALLENGED','Distinct sweep-mutant mirror shares OP58 false path; site943, not905.');
put('200','SUPPORTED-STATIC','Correct producer row193 and OP40 semantic flip; OPEN extent site904 wrong (actual940); downstream failed import unobserved.');
put('201','CONDITIONAL','Silent closure-record deletion falsifies history-preservation at threshold1 trace open then assent; old standalone fixture receipt is not exact current atom evidence.');
put('202-204','SUPPORTED-STATIC','Actual KelGroups carrier projections; states premise-provided Nodup/coherence, not production guard behavior.');
put('205','SUPPORTED-STATIC','tryEnact_eq_of_enacts follows definition of Enacts and rfl; no production mutation sensitivity.');
put('206','SUPPORTED-STATIC','Bypass duplicate admission: existing member admitted, member-absent conjunct false. Nonadmin refusal and growth-on-absent premises are distinct and may survive.');
put('207','CHALLENGED','Exactly one real base_change_runs_hook row. OP58 upstream tryEnactBase_runs_hook survives, so proposed failure cascade has no source.');
if(Object.keys(notes).length!==207)throw Error('missing '+map.filter(x=>!notes[x.row]).map(x=>x.row));const rows=map.map(({row,c})=>({row,operation:c[0],identity:c[1],candidateVerdict:c[2],candidateEvidence:c.at(-1),site:src.find(x=>x.name===c[1])?.site||'PHANTOM-WITHDRAWN',...notes[row]}));fs.writeFileSync('handoffs/evidence/row-review-207.json',JSON.stringify(rows,null,2)+'\n');fs.writeFileSync('handoffs/ROW-REVIEW-207.md','# Independent review of all 207 frozen map rows\n\nEach row was assessed against declaration identity, source property, proposed atom, proof body where relevant, and the original mandate. SUPPORTED-STATIC means the stated narrow source deduction is supported; it is never observed RED/GREEN, complete coverage, or acceptance. BASELINE-ONLY and DEPENDENCY-ONLY do not discharge semantic mutation obligations. CONDITIONAL and OPEN remain required work. Global plan/measurement findings apply even where the narrow source deduction is supported.\n\n| Row | Operation / identity / site | Audit disposition | Evidence and required correction |\n|---|---|---|---|\n'+rows.map(x=>`| ${x.row} | ${x.operation}; ${x.identity}; ${x.site} | ${x.status} | ${x.note.replaceAll('|','/')} |`).join('\n')+'\n');console.log('207 rows',Object.fromEntries([...new Set(rows.map(x=>x.status))].map(k=>[k,rows.filter(x=>x.status===k).length])));
