const fs=require('fs');const original=fs.readFileSync('admitted/original-audit/REQUIREMENT-LEDGER.md','utf8').split('\n').filter(l=>/^\| (A-|P1|D[456] |B-|OUT-)/.test(l)).map(l=>l.split('|').slice(1,-1).map(x=>x.trim()));const v={
'A-01':['CLOSED','Own detached source SHA/clean/zero-olean checks; independent-source-inventory.json. No mutation of source.'],
'A-02':['CLOSED','Own /proc launch and own-session active model independently verified; first journal START includes both. identity.md.'],
'A-03':['CLOSED','Own named pane/window bound; no other seat inspected/contacted. Fresh commission and session, no delegation.'],
'A-04':['CLOSED','All admitted49 and original323 hashes checked; full relationship preserved, no wrapper omission treated as exclusion.'],
'A-05':['CLOSED','Full D1-D6, eight original findings,207 rows,81 helpers,43 file tables assessed. Original corrections given actual precedence, not ignored.'],
'A-06':['CLOSED','Own execution0 at every project layer; local parsing/hashing/report writes only.'],
'P1A-01':['CLOSED','Independent namespace/site parser finds239 declarations/224 short spellings; source count is not fresh compiled count.'],
'P1A-02':['CLOSED','Retained1213 names/class rows and all239 public/private matches mechanically checked; no rerun.'],
'P1A-03':['CLOSED','All158 authored/81 helper labels mapped to actual statements; every identity retained; no helper exemption inferred.'],
'P1A-04':['CLOSED','All974 remainder names listed/classified by retained rule; bounded static name accounting only, not compiler-mechanism proof.'],
'P1A-05':['CLOSED','All81 explicit static antecedent instances in HELPER-REVIEW-81; corrected membership/option/inequality instances valid.'],
'P1A-06':['PARTLY','Actual root/hook source inspected; extra role guards named. Complete per-branch reached binding account remains S-02.'],
'P1A-07':['PARTLY','131 atom IDs present, economic conjuncts substantially enumerated; vote/base/cleanup/refusal/binding atoms remain grouped or absent. S-02.'],
'P1A-08':['PARTLY','561 relation lines preserve names but wrong Benact-met assignments, broad tags and unallocated current falsifiers persist. S-02/S-03.'],
'P1A-09':['CLOSED','no_expiry arbitrary event and semantic preservation premise correctly restored; bound to actual source.'],
'P1A-10':['CLOSED','Fixed-view Reach transport distinguished from present boot/apply/admission producers; S5 connection remains a question.'],
'P1A-11':['PARTLY','Seven root wrappers and eight TraceTests pairs are distinct, intact. Wrong mirror references and unsupported inherited RED paths remain S-05/S-06.'],
'P1B-01':['CLOSED','43 distinct campaign files verified against frozen tree and lossless table index; headers not receipts.'],
'P1B-02':['PARTLY','Some original transcription repairs stand; E-TOJSON counts/state, t62 TRACE/terminal states, VI and other omitted rows remain S-01.'],
'P1B-03':['PARTLY','Recoverable instrument/log hashes exist; complete per-experiment seven-field records and search bounds remain absent. S-01.'],
'P1B-04':['PARTLY','Report-sha/candidate distinction repaired; recovered bytes not sufficient for current reuse. Required reassessment still misbinds t57 and underuses t62 records.'],
'P1B-05':['PARTLY','No current coverage claimed; historical/fixture/definition/checker distinctions partly sound, but speculative cross-property mappings persist.'],
'P1C-01':['PARTLY','Step module timings and historical mixed layers documented; cold, independent check/replay and complete closure timings unmeasured. S-07.'],
'P1C-02':['PARTLY','Historical one-line donate mutation and specific diagnostic form a narrow real interaction; different from current OP22 exact atom and lacks isolation.'],
'P1C-03':['OPEN','Actual historical mutation used candidate source root; restore cleanliness does not prove separation. Prospective scratch does not cure history.'],
'P1C-04':['OPEN','No complete measured per-row/per-batch or shared-compilation comparison.18-run request omits necessary classes and implementation.'],
'P1C-05':['CLOSED','Historical4-against3 then separately granted OP10 =>5 substantive/3 targeted preserved; auditor0 separate from author3/3 submissions.'],
'P1D-01':['OPEN','No complete exact operation registry or measured numeric sufficient ceiling; withdrawn143+1 and proposed18 are not accepted.'],
'P1D-02':['PARTLY','Source239 and map158 authored retained; semantic axis/operation allocations incomplete,8 false OPEN-insensitivity claims, exemptions absent.'],
'P1D-03':['PARTLY','Source import graph exists; exact loading/observation paths unexecuted and same-module universal blocking false. S-05/S-07.'],
'D4':['CLOSED','Current checkpoint claims no coverage; own execution/kill/survivor sets empty. Future homogeneous per-identity six-set reconciliation remains required.'],
'D5':['PARTLY','Phase1/checkpoint/ungranted boundary preserved; its required measured costs and numeric phase plan are incomplete. Successor is separately commissioned, not grant.'],
'D6':['PARTLY','VOID and actual known ambiguity evidence preserved in onward file; final LEAN-CLARITY deliverable remains later work, no fabricated reader experiment.'],
'B-01':['PARTLY','Current source statements/fence untouched; historical candidate-source mutation retained as blocking past noncompliance.'],
'B-02':['CLOSED','Original owner actual EOF FINAL EVENT/STOPPING with counters supersedes stale Next; own final EOF receipt delivered separately.'],
'OUT-01':['CLOSED','One terminal findings report,36-row ledger,207-row review,81-helper review,onward,campaign,successor,evidence manifest and own EOF journal.']};
if(original.length!==36)throw Error(original.length);let rows=original.map(r=>{if(!v[r[0]])throw Error(r[0]);return{id:r[0],requirement:r[1],status:v[r[0]][0],evidence:v[r[0]][1]}});let counts=Object.fromEntries([...new Set(rows.map(x=>x.status))].map(k=>[k,rows.filter(x=>x.status===k).length]));fs.writeFileSync('handoffs/REQUIREMENT-LEDGER.md','# Full mandate requirement ledger — independent final static audit\n\nAll36 original requirement IDs retained. Status is at its named observable and evidence layer, not acceptance or mutation coverage. PARTLY/OPEN required inputs remain blocking unless the mandate explicitly assigns them to a later deliverable (D6). Original finding dispositions are separately reported; row counts are not finding counts.\n\nCounts: '+JSON.stringify(counts)+'.\n\n| ID | Original requirement | My status | Evidence / remaining requirement |\n|---|---|---|---|\n'+rows.map(x=>`| ${x.id} | ${x.requirement} | ${x.status} | ${x.evidence} |`).join('\n')+'\n\nD1 identity extent is established statically; D1 semantic extent and D2 relevant mutation evidence remain incomplete. D3 historical assessment remains incomplete. D4 has no coverage claim. D5 cost/plan requirements remain incomplete. D6 is preserved with actual evidence and its VOID limitation. All required work returns to the commissioner under the bounded successor recommendation.\n');console.log(counts);
