import fs from 'node:fs';import {execFileSync} from 'node:child_process';import crypto from 'node:crypto';
const root='/tmp/reactivegas/ms2/e-lean-compliance/candidate-auditor-s4b-codex-r3';const [mode,id]=process.argv.slice(2);const hash=s=>crypto.createHash('sha256').update(s).digest('hex');const dir=`${root}/controls/${id}`;
if(mode==='apply'){
 const variants={S02:[['lean/Reactivegas/Predicates.lean','\ndef auditUnannotated (s : State) := s.conti = []\ndef auditAlias (s : State) := auditUnannotated s\ndef auditPropParam (_ : Prop) : Nat := 7\n']],S03:[['lean/Reactivegas/Predicates.lean','\ndef auditTheoremless (s : State) : Prop := s.conti = []\n'],['lean/Reactivegas/Mirrors.lean','\ndef auditTheoremlessB (s : State) : Bool := decide (s.conti = [])\n']],S04:[['scripts/check-lean-mirrors',null]],S06:[['lean/Reactivegas/Predicates.lean','\nopaque auditOpaque (s : State) : Prop := s.conti = []\n']]};
 fs.mkdirSync(dir,{recursive:true});const identities=[];
 for(const [path,suffix] of variants[id]){const old=fs.readFileSync(path);const base=execFileSync('git',['show',`HEAD:${path}`]);if(!old.equals(base))throw Error(`not pristine ${path}`);const raw=suffix===null?Buffer.from('#!/usr/bin/env bash\nexit 0\n'):Buffer.concat([old,Buffer.from(suffix)]);const stem=path.replaceAll('/','__');fs.writeFileSync(`${dir}/${stem}.original`,old);fs.writeFileSync(`${dir}/${stem}.mutant`,raw);fs.writeFileSync(path,raw);identities.push({path,stem,original:hash(old),mutant:hash(raw)});}
 fs.writeFileSync(`${dir}/identities.json`,JSON.stringify(identities,null,2)+'\n');fs.writeFileSync(`${dir}/mutant.diff`,execFileSync('git',['diff','--',...identities.map(i=>i.path)]));console.log(`APPLIED ${id}`);
}else if(mode==='restore'){
 const ids=JSON.parse(fs.readFileSync(`${dir}/identities.json`));for(const i of ids){if(hash(fs.readFileSync(i.path))!==i.mutant)throw Error(`concurrent edit ${i.path}`);fs.writeFileSync(i.path,fs.readFileSync(`${dir}/${i.stem}.original`));if(hash(fs.readFileSync(i.path))!==i.original)throw Error('restore failed');}fs.writeFileSync(`${dir}/restoration.json`,JSON.stringify({time:new Date().toISOString(),identities:ids,git:execFileSync('git',['status','--porcelain=v1'],{encoding:'utf8'})},null,2)+'\n');console.log(`RESTORED ${id}`);
}else throw Error('apply/restore');
