import fs from 'node:fs';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const r='/tmp/reactivegas/ms2/e-lean-compliance/candidate-auditor-s4b-codex-r3';const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const receipts=fs.readdirSync(`${r}/evidence`).filter(x=>x.endsWith('.receipt.json')).map(x=>({id:x.slice(0,-13),...JSON.parse(fs.readFileSync(`${r}/evidence/${x}`))})).sort((a,b)=>a.start.localeCompare(b.start));
const final=receipts.find(x=>x.id==='S05'),axiom=receipts.find(x=>x.id==='AXIOMS');if(!final||!axiom)throw Error('Required final receipts absent');
const counts=JSON.parse(fs.readFileSync(`${r}/evidence/counters.json`));
const direct=receipts.filter(x=>x.kind==='substantive').length,targeted=receipts.filter(x=>x.kind==='targeted').length;if(direct!==counts.substantive||targeted!==counts.targeted)throw Error('counter mismatch');
let commands='# Actual command and resource ledger\n\nEvery Lean/build invocation below has complete separate stdout/stderr and before/after Git/free-space snapshots. ACCIDENTAL-SETUP is a conservatively charged non-Lean failure with its diagnostic-capture limitation explicit; it establishes no audit result. Exit is the actual process status. Failed and warm calls are included. Source reads, hashing, generation and file copying are free under the brief. One tool call containing recursive removal was rejected before execution; it launched no subprocess/build and is not a hidden failed build. The safer replacement moved the old .lake into retained evidence before the final run.\n\n';
commands+=`Totals: **${direct}/8 substantive, ${targeted}/60 targeted**, across submission 1. Owner input remains 8/8 and 42/60; S4-A remains 3/3 and 15/20. No refund/reset/ceiling increase.\n\n| ID | Class | Exit | Seconds | Cache | Receipt SHA-256 | Command |\n|---|---|---:|---:|---|---|---|\n`;
for(const x of receipts){const cache=x.id==='ACCIDENTAL-SETUP'?'not applicable':['S01','S05'].includes(x.id)?'cold Lean (zero oleans); Nix store reuse not excluded':'warm candidate library';commands+=`| ${x.id} | ${x.kind} | ${x.code} | ${(x.start&&x.end?((Date.parse(x.end)-Date.parse(x.start))/1000).toFixed(3):'unknown')} | ${cache} | ${sha(`${r}/evidence/${x.id}.receipt.json`)} | ${x.argv.map(a=>JSON.stringify(a)).join(' ')} |\n`;}
fs.writeFileSync(`${r}/handoffs/COMMAND-RECEIPTS.md`,commands);
const muts=JSON.parse(fs.readFileSync(`${r}/evidence/mutation-diagnostics.json`));let mutation='# Per-atom mutation receipt\n\n44 retained single-definition executable mutants, each type-valid through its definition, with original theorem statement/proof suffix byte-identical. All errors fall within the target theorem; no earlier definition error, parser/import failure, or unrelated theorem failure is credited. These are kernel elaboration sensitivity observations over this finite operator ledger, not a claim about all possible mutants. Target diagnostics include explicit altered equations, guards, and composed properties.\n\n| ID | Definition / atom | Original theorem | Verdict | Mutant SHA-256 | Diagnostic SHA-256 |\n|---|---|---|---|---|---|\n';
for(const m of muts)mutation+=`| ${m.id} | ${m.def} / ${m.atom} | ${m.thm} | ${m.targetHit&&!m.defError&&m.exit===1?'KILLED':'BLOCKED'} | ${m.mutantSha} | ${sha(`${r}/evidence/${m.id}.stdout`)} |\n`;
mutation+='\nP01 and P07 are separate: their relatum mutants are red, but the executable-body probes E-P01-R/E-P07-R survive. Thus 17/19 correspondence identities have the required executable-definition kill; the two remaining identities have valid proofs and truthful narrower relatum evidence, but do not receive an executable-body KILLED designation. See F02. WIT, E-P01-PROBE and E-P07-PROBE and ACCIDENTAL-SETUP are four counted setup failures (three Lean, one conservatively charged non-Lean), excluded from valid mutant totals. I-NEG is the intended empty-denominator control, not a setup failure.\n';fs.writeFileSync(`${r}/handoffs/MUTATION-RECEIPTS.md`,mutation);
// Replace initialized row assessments with terminal row-specific observations.
let ledger=fs.readFileSync(`${r}/handoffs/CAMPAIGN-LEDGER.md`,'utf8');fs.writeFileSync(`${r}/handoffs/CAMPAIGN-LEDGER-pre-execution.md`,ledger);
const special={
 R7:['PARTLY','BLOCKED','I-POS confirms current 24; S06 + I-OPAQUE prove new opaque owned predicate omitted, F01'],R8:['PARTLY','BLOCKED','S02 red for def/alias; S06 green for opaque without counterpart, F01'],C2:['PARTLY','BLOCKED','S02 named missing ordinary counterpart; S06 silently omitted new opaque predicate, F01'],R9:['PARTLY','BLOCKED','S03 names ordinary missing theorem/orphan; opaque identity can evade all correspondence accounting, F01'],C3:['CLOSED','KILLED','S03 exit1, auditTheoremless and auditTheoremlessB named separately from S02'],R11:['PARTLY','BLOCKED','M01-M44 kill 17 identities; P01/P07 body mutations survive, F02'],C5:['PARTLY','BLOCKED','P01 relatum red; E-P01-BUILD/R both exit0 with changed membership behavior, F02'],C11:['PARTLY','BLOCKED','P07 relatum red; E-P07-BUILD/R both exit0 with changed permission behavior, F02'],
 'V2-ID':['PARTLY','BLOCKED','Current I-POS denominator agrees per identity, future opaque admission omitted, F01'],
 'S4-AUD03':['PARTLY','BLOCKED','Current axes reconciled; opaque-kind filtering removes newly required identity without classification, F01'],
 'S4-COMP01':['PARTLY','BLOCKED','F01/F02 remain owned by commissioner %503 through this report; no milestone acceptance or closure inferred'],
 'A-CLASSIFIER':['PARTLY','BLOCKED','I-NEG/I-POS and S02 establish sort, alias and imported-def cases; S06 omits opaqueInfo, F01']};
const controlMap={C6:'M01-M03',C7:'M04-M07',C8:'M08',C9:'M09-M10',C10:'M11',C12:'M12-M14',C13:'M15-M16',C14:'M17-M18',C15:'M19-M21',C16:'M22-M23',C17:'M24',C18:'M25',C19:'M26-M29',C20:'M30-M31',C21:'M32-M34',C22:'M35-M41',C23:'M42-M44'};
const inspections=new Set(['S4-A08','S4-A09','S4-A10','S4-A12','S4-A13','S4-A14','S4-A15','S4-A16','S4-A17','S4-A18','S4-B01','S4-AUD01','S4-AUD04','S4-F01','S4-F02','S4-F03','S4-COMP02','R1','R2','R3','R5','R16','R17','R18','V2-BASE','N1-COUNT','N4-BASE','B-MUT','B-PLAN','B-LABEL','N001-LEDGER','N001-COUNTERS','N001-PREV','EX-A','EX-B','ONWARD']);
const specific={
 C1:'S01 exact clean candidate just lean exit0, cold Lean, receipt and compiled modules observed',C4:'S04 actual just lean exit1 on present exit0 checker, MIRROR-RECEIPT-ABSENT; executable restored',R10:'S04 same permanent path rejects present unconditional-success checker; no exit127 credited',R12:'44 separate target diagnostic receipts plus separate P01/P07 and body-control observations; no first-failure masking',R13:'S05 fresh .lake followed by AXIOMS; final exact source identity, both streams retained',C24:'AXIOMS transitive public theorem axiom sets, plus S05 whole-project axiom gate',C25:'AXIOMS and S05 both streams checked for PANIC; positive module/theorem counts recorded',C26:'S05 exact restored candidate just ci actual exit'+final.code,
 R4:'Diff: no duplicate Bool for P01/P07; original theorem bytes and WIT-R existing-expression evaluations',R6:'WIT-R threshold 2/1 yields true/false; M44 fixed-threshold mutant red',R14:'WIT-R duplicate balances/default zero with nonzero values; universal arbitrary-state statements and M04-M07/M19-M21/M35-M44',R15:'Exact final theorem types carry no new well-formedness premises; generic DecidableEq only on new Enacts pair',
 'V2-DEFEQ':'P01/P07 relatum-vs-body distinction explicitly retained; accuracy does not close C5/C11 body requirement',
 'V2-EVID':'Four setup failures retained/spent (three Lean, one conservatively charged non-Lean); no failed setup or body survivor credited as kill',
 'A-EQUALITY':'New Enacts pair uses DecidableEq alpha; WIT-R distinguishes Nat payloads 7 and 8; M31 state-equality mutant red',
 'B-MUT':'All mutant sources retained; controls/S02,S03,S04,S06 restoration.json; expression-control restoration receipt; final Git clean',
 'B-PLAN':'Pre-START plan hash 98c97381...; append-only measured refinements; final '+direct+'/8 and '+targeted+'/60',
 'N001-COUNTERS':'Owner read-only ledger 8/8+42/60, S4-A3/3+15/20, prior auditor0/0; unknown ticket aggregate authorized',
 'N001-PREV':'Both admitted terminal predecessor reports and ledger preserved, no inherited semantic closure',
 'EX-A':'Brief express authorization QUALITY-S4B-TERMINAL-CONTRACT-RECOVERY-20260905 item2; pane %564 dedicated sibling window',
 'EX-B':'Admitted b9e8c467... ruling item2 replaces exact ticket-wide history prerequisite with S4-B campaign history',
 'ONWARD':'Explicit final empty witnessed unrelated-findings set in ONWARD-DISCOVERIES.md, commissioner %503 only'};
ledger=ledger.split('\n').map(line=>{if(!line.startsWith('| ')||line.startsWith('| Row |')||line.startsWith('|---'))return line;const cols=line.split('|');const id=cols[1].trim();let verdict='CLOSED',state=inspections.has(id)?'NOT-A-MUTATION-CLAIM':'VERIFIED',obs=specific[id]||'CLASSIFICATION.md current compiled identity, authority, proof and value evidence; see exact per-identity rows',label=inspections.has(id)?'inspection':'new-execution';if(controlMap[id]){state='KILLED';obs=controlMap[id]+' separate intended original-theorem failures, WIT-R positive/negative values and AXIOMS proof trust';}if(special[id])[verdict,state,obs]=special[id];return `| ${id} | ${cols[2].trim()} | BLOCKING | ${verdict} | ${state} | ${obs} | ${label} |`;}).join('\n');
ledger+='\n## Terminal accounting\n\n'+`Actual ${direct}/8 substantive, ${targeted}/60 targeted; no overrun. 44 executable mutant atoms KILLED; two executable-body sensitivity rows BLOCKED (F02); future opaque discovery BLOCKED (F01). Administrative/path/authority observations explicitly are not mutation kills. Every row has a terminal assessment; remaining blocking requirements are returned with exact evidence, never residual/advisory. Stopped at the bounded set-point with findings, not at budget exhaustion or a no-findings tail.\n`;
fs.writeFileSync(`${r}/handoffs/CAMPAIGN-LEDGER.md`,ledger);
console.log(JSON.stringify({direct,targeted,final:final.code,axioms:axiom.code,rows:ledger.split('\n').filter(l=>l.startsWith('| ')&&!l.startsWith('| Row |')).length}));
