import fs from 'node:fs';
import {spawn,spawnSync} from 'node:child_process';
import crypto from 'node:crypto';
const root='/tmp/reactivegas/ms2/e-lean-compliance/candidate-auditor-s4b-codex-r3';
const [kind,id,...argv]=process.argv.slice(2);
if(!['substantive','targeted'].includes(kind)||!id||!argv.length)throw Error('usage: kind id command args');
const countPath=`${root}/evidence/counters.json`;
const counts=fs.existsSync(countPath)?JSON.parse(fs.readFileSync(countPath)): {substantive:0,targeted:0};
if(counts[kind]>=(kind==='substantive'?8:60))throw Error('BUDGET WOULD OVERRUN');
const prefix=`${root}/evidence/${id}`;
const out=fs.openSync(`${prefix}.stdout`,'wx'),err=fs.openSync(`${prefix}.stderr`,'wx');
counts[kind]++;fs.writeFileSync(countPath,JSON.stringify(counts)+'\n');
const snap=()=>({git:spawnSync('git',['status','--porcelain=v1'],{encoding:'utf8'}).stdout,head:spawnSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim(),df:spawnSync('df',['-B1','.'],{encoding:'utf8'}).stdout});
const start=new Date().toISOString(),before=snap();
const append=(tag,msg)=>fs.appendFileSync(`${root}/STATUS.md`,`${new Date().toISOString()}  ${tag}  ${msg}\n`);
append('COMMAND-START',`${id} kind=${kind} counters=${counts.substantive}/8,${counts.targeted}/60 command=${JSON.stringify(argv)}`);
fs.writeFileSync(`${prefix}.start.json`,JSON.stringify({start,kind,argv,counts,before},null,2)+'\n');
console.log(`RUN ${id} ${kind} counters=${JSON.stringify(counts)}`);
const child=spawn(argv[0],argv.slice(1),{stdio:['ignore',out,err]});
child.on('error',e=>fs.writeSync(err,String(e)));
child.on('close',(code,signal)=>{fs.closeSync(out);fs.closeSync(err);const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const receipt={start,end:new Date().toISOString(),kind,argv,code,signal,counts,before,after:snap(),stdout:{path:`${prefix}.stdout`,sha256:hash(`${prefix}.stdout`)},stderr:{path:`${prefix}.stderr`,sha256:hash(`${prefix}.stderr`)}};fs.writeFileSync(`${prefix}.receipt.json`,JSON.stringify(receipt,null,2)+'\n');append('COMMAND-END',`${id} exit=${code} signal=${signal} receipt=${prefix}.receipt.json counters=${counts.substantive}/8,${counts.targeted}/60`);console.log(JSON.stringify(receipt));process.exitCode=code??1;});
