AUDIT_PACKET_SPEC_V2
COUNTERS	/tmp/reactivegas/ms2/e-lean-compliance-sol-20260906/audit-packets/i92s-sub1-I1-sol-v2/counters
INPUT	dispatch-receipt	/tmp/reactivegas/ms2/e-lean-compliance-sol-20260906/ledgers/dispatch-preflight-receipt-I1-sol-v1.md
INPUT	campaign-ledger	/tmp/reactivegas/ms2/e-lean-compliance-sol-20260906/ledgers/current-campaign-ledger.md
INPUT	row-ledger	/tmp/reactivegas/ms2/e-lean-compliance-sol-20260906/ledgers/current-row-ledger.md
ROLE	dispatch-preflight-receipt	dispatch-receipt
ROLE	current-campaign-ledger	campaign-ledger
ROLE	current-row-ledger	row-ledger
INPUT	audit-scope	/tmp/reactivegas/ms2/e-lean-compliance-sol-20260906/handoffs/I1-AUDIT-SCOPE-V1.md
INPUT	commissioner-substitution	/tmp/reactivegas/ms2/e-lean-compliance-sol-20260906/handoffs/I92-COMMISSIONER-SUBSTITUTION-V1.md
INPUT	operator-role-substitution	/tmp/reactivegas/ms2/artifacts/ROLE-SUBSTITUTION-CODEX-SOL-20260906.md
INPUT	mandate	/tmp/reactivegas/ms2/e-lean-compliance/handoffs/I92-SUCCESSOR-MANDATE-V2.md
INPUT	issue-92	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/inputs/ISSUE-92.md
INPUT	prior-adjudication	/tmp/reactivegas/ms2/e-lean-compliance/handoffs/I92-SUB1-ADJUDICATION-AND-TERMINAL-TOPOLOGY.md
INPUT	submission-manifest	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/MANIFEST.sha256
INPUT	submission-readme	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/README.md
INPUT	submission-receipt	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/receipt.md
INPUT	submission-reliance	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/RELIANCE.md
INPUT	commit-provenance-identities	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/identities.txt
INPUT	commit-diff-quality	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/quality.diff
INPUT	commit-diff-c1	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/c1.diff
INPUT	commit-paths-quality	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/quality-paths.txt
INPUT	commit-paths-combined	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/combined-paths.txt
INPUT	combined-construction	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/construction.txt
INPUT	candidate-check-lean-mirrors	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/check-lean-mirrors
INPUT	candidate-lake-roots-main	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/lake-roots-Main.lean
INPUT	candidate-lake-roots-lakefile	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/lake-roots-lakefile.lean
INPUT	candidate-lake-roots-gitignore	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/lake-roots.gitignore
INPUT	n1-runner	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/n1-run.sh
INPUT	n1-target-manifest	/tmp/reactivegas/ms2/e-lean-compliance/i92-grok-owner/handoffs/SUBMISSION-1/n1-target.manifest
TOOL	bash	bash
TOOL	git	git
TOOL	sha256sum	sha256sum
TOOL	grep	grep
TOOL	awk	awk
TOOL	sed	sed
TOOL	node	node
TOOL	jq	jq
TOOL	nix	nix
TOOL	diff	diff
TOOL	sort	sort
