import fs from 'node:fs';import crypto from 'node:crypto';
const rt='/tmp/reactivegas/ms2/e-lean-compliance/candidate-auditor-s4b-sub2-final-r2',f=rt+'/instruments/full-v2',src='/code/reactivegas-66-s4b-audit5',lib=src+'/lean/.lake/build/lib/lean',lean='/nix/store/4gr3n4nrp0xxgykyyzdxi3xjj2ikn5x1-lean4-4.25.0/bin/lean';
const h=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const bind=p=>({path:p,sha256:h(p)});
const common=[bind(rt+'/instruments/candidate-inputs.sha256'),bind(rt+'/evidence/M1/oleans.sha256'),bind(rt+'/instruments/modules.txt')];
const rows=[];
function add(id,argv,obligation,observation,files=[],prerequisites=['M1-S','M1R-T'],world='clean M1-S module library; separate elaboration environment',charge='targeted',cwd=src+'/lean'){
rows.push({id,charge,layer:charge==='substantive'?'whole mandatory/build path':'single leaf elaboration or named artifact assertion',argv,cwd,obligation,observation,inputs:[...common,...files.map(bind)],inputRelation:'269 frozen tracked candidate inputs; M1-S 30 retained olean digests. Generated-world module outputs are hashed after their producer and before consumer. No owner outputs.',world,prerequisites,outputs:[rt+'/evidence/full-v2/'+id+'.stdout',rt+'/evidence/full-v2/'+id+'.stderr',rt+'/evidence/full-v2/'+id+'.json'],stop:'No implicit retry. Setup failures charged and establish no semantic result. Any changed discovery set, unresolved sort, partial output, dependency drift, or resource-bound breach stops dependent closure and is named; never truncate.'});}
function leaf(id,file,ob,obs,lp=lib,pre=['M1-S','M1R-T'],extra=[]){add(id,['timeout','--signal=TERM','--kill-after=10s','300s','env','LEAN_PATH='+lp,lean,'-DautoImplicit=false',...extra,f+'/'+file],ob,obs,[f+'/'+file],pre,lp);}
for(const w of JSON.parse(fs.readFileSync(f+'/worlds.json'))){const world=rt+'/worlds/'+w.id;const command=w.id==='S09'?['bash',f+'/base-build.sh']:['just',w.id==='S10'?'ci':'lean'];add(w.id,['timeout','--signal=TERM','--kill-after=30s','1800s','nix','develop','--quiet','-c',...command],w.obligation,w.id==='S01'||w.id==='S09'||w.id==='S10'?'exit 0; complete raw output; S10 fresh .lake and clean final candidate required':({S02:'exit nonzero at MIRROR-UNCOVERED naming BOTH auditMissingCounterpart and auditOpaquePredicate; import reached',S03:'exit nonzero at MIRROR-THEOREM-MISSING naming auditMissingTheorem',S04:'exit nonzero MIRROR-IMPORT-REACH-GAP for Reactivegas.AuditFuture; no predicate-discovery credit',S05:'exit nonzero MIRROR-UNCLASSIFIED naming actual theorem declarations',S06:'present executable noop exits 0 but mandatory receipt/nonce guard exits nonzero MIRROR-RECEIPT-ABSENT',S07:'single body isMember=false; record actual earlier module failure; no downstream helper credit',S08:'single production close permission bypass; record actual whole-path failure; no selected-chain credit'}[w.id]),[f+'/worlds.json',f+'/world-prepare.mjs',...(w.id==='S09'?[f+'/base-build.sh',f+'/base-modules.txt']:[])],w.id==='S10'?['S01','S02','S03','S04','S05','S06','S07','S08','S09']:['M1-S','M1R-T'],world+'; '+(['S09','S10'].includes(w.id)?'cold, no .lake':'private copy M1-S cache; exact specified edit only'), 'substantive',world);}
for(const a of JSON.parse(fs.readFileSync(rt+'/planning/atoms.json'))){leaf(a.id,'atoms/'+a.id+'.lean','R11/R12 C5-C23 '+a.obligation+'; '+a.definition+' -> '+a.theorem,'Single executable-body edit '+JSON.stringify(a.old)+' -> '+JSON.stringify(a.replacement)+'. #check definition success, original target proof error within '+a.proofLines.join('-')+' and semantic mismatch required; downstream or setup errors do not count. Positive S01.',lib,['S01']);rows.at(-1).atom=a;}
for(const p of ['P01','P07']){
 const target=p==='P01'?'KelGroups/Types':'Reactivegas/Step';const shadow=rt+'/worlds/shadow-'+p;
 leaf(p+'-compile','shadows/'+p+'/'+target+'.lean',p+' isolated single-module shadow compilation','exit0 generates only '+shadow+'/'+target+'.olean; fresh separate directory, no stale sibling mutant; record input and output hashes',lib,['S01'],['--root='+f+'/shadows/'+p,'-o',shadow+'/'+target+'.olean']);rows.at(-1).outputs.push(shadow+'/'+target+'.olean');
 leaf(p+'-neg',p+'-chain.lean',p+' amended body/consumer sensitivity and distinguishing witness',p==='P01'?'original two promoted helpers fail at their proof bodies; original corr survives; witness present=false absent=false duplicates=2':'original step_close_inv proof fails on permission mismatch; original corr survives; selectedBinding=true authorized=true forbidden=true preservesOther=true amount=true; outer dependent theorem not independently body-killed',p==='P01'?shadow:shadow+':'+lib,[p+'-compile']);
 leaf(p+'-pos',p+'-chain.lean',p+' otherwise-identical positive selected chain and nondegenerate witness',p==='P01'?'exit0, same driver bytes, present=true absent=false duplicates=2':'exit0, same driver bytes, selectedBinding=true authorized=true forbidden=false preservesOther=true amount=true',lib,[p+'-neg']);
 leaf(p+'-relatum',p+'-relatum.lean',p+' original inline/value-parametric relation accurately scoped','original correspondence fails under changed predicate relatum; NEVER implementation kill',lib,['S01']);
}
for(const [id,ob,obs]of [
['EconomyWitnesses','R14/P02-P06/P08-P10/P12 nondegenerate finite decisions','all 28 named rows true; duplicate first lookup, absent defaults, nonzero effects, counterexamples'],
['GroupWitnesses','K1-K5 V1-V3 callable policy/generic payload witnesses','all 29 named rows true including 6 SweepReady guards and Nat payload inequality'],
['WitnessNegative','witness assertion can-fail instrument','all rows reached; sentinel false then WITNESS-FAILED; not production mutant'],
['Exceptions','P11 V4 R0 exception logical and executable evidence; Reach/Reach.below exact inductive scope','14 constructor projections rfl and true/false evaluation per constructor; R0 nonzero decision both ways; V4 real-question changed/preserved; print Reach and generated below'],
['ReachDecision','Reach bounded Decidable availability query','stalled synth succeeds then concrete Reach synth unavailable; NOT undecidability nor NOT-REQUIRED authority'],
['EmptyInventory','independent census nonempty self-control','own instrument exits nonzero at zero owned module guard; partial output no extent'],
['UnknownInventory','independent census unresolved-sort self-control','own instrument retains conservation sort-undecided then fails; no closure of historical production census path'],
['AxiomsNegative','axiom allowed-list self-control','auditForbiddenTheorem rejected because auditForbidden; iterate every theorem before final failure']])leaf(id,id+'.lean',ob,obs,lib,['S01']);
leaf('BaseInventory','BaseInventory.lean','R1/R5/R15 source->compiled accepted-base universe for original Expr preservation','complete nonempty capture bound20000decl/256MiB;27 input modules not denominator',rt+'/worlds/S09/lean/.lake/build/lib/lean',['S09']);
leaf('FinalInventory','FinalInventory.lean','R7/R13 final compiled owned extent and sort classification, every declaration','complete nonempty capture bound20000decl/256MiB; stop on any identity drift;29 input modules not denominator',rt+'/worlds/S10/lean/.lake/build/lib/lean',['S10']);
leaf('Axioms','Axioms.lean','C24/R13 final every owned theorem #print axioms','only propext Classical.choice Quot.sound; dynamic nonempty theorem list <=20000 must equal final measured theorem identity set',rt+'/worlds/S10/lean/.lake/build/lib/lean',['S10','FinalInventory','AxiomsNegative']);
for(const [mode,ob,obs,pre] of [
['census-controls','R7 own census completeness failure controls','baseline accepted; empty, omitted conservation, unknown-sort conservation, false-home conservation separately rejected',['M1R-T']],
['expr-controls','R1/R5 own Expr comparison failure controls','self equal; changed type/body/levels/kind and missing conservation separately rejected',['M1R-T']],
['expr-compare','R1/R5/R15 every original compiled declaration statement/proof/definition preservation','all base identities present with identical kind/typeExpr/valueExpr/levelParams hashes; no fixed extent; fail names original identity',['BaseInventory']],
['final-reconcile','R7 final mandatory receipt versus independent discovery, restoration','exact predicate-name sets, module-name sets and complete M1R/final Expr sets equal; no quota',['FinalInventory','S10']]])add(mode,['timeout','300s','node',f+'/data-checks.mjs',mode],ob,obs,[f+'/data-checks.mjs'],pre,'immutable complete metadata and final S10 receipt', 'targeted',rt);
for(const mode of ['controls','final'])add('panic-'+mode,['timeout','60s','node',f+'/panic-check.mjs',mode],'C25 both-stream PANIC at absence '+mode,mode==='controls'?'clean accepted, stdout stderr and both injected panic strings rejected':'S10 FinalInventory Axioms EconomyWitnesses GroupWitnesses Exceptions P01-pos P07-pos both streams absent',[f+'/panic-check.mjs'],mode==='controls'?['M1R-T']:['S10','FinalInventory','Axioms','EconomyWitnesses','GroupWitnesses','Exceptions','P01-pos','P07-pos'],'immutable per-command output streams','targeted',rt);
const counts={substantive:1,targeted:2};for(const r of rows)counts[r.charge]++;if(counts.substantive>12||counts.targeted>80)throw Error(JSON.stringify(counts));
fs.writeFileSync(f+'/COMMANDS.json',JSON.stringify(rows,null,2)+'\n');
fs.writeFileSync(f+'/FIT.json',JSON.stringify({alreadySpent:{substantive:1,targeted:2},future:{substantive:rows.filter(r=>r.charge==='substantive').length,targeted:rows.filter(r=>r.charge==='targeted').length},totalPlanned:counts,ceiling:{substantive:12,targeted:80},unallocated:{substantive:12-counts.substantive,targeted:80-counts.targeted},historical:{substantive:6,targeted:59},campaignPlanned:{substantive:6+counts.substantive,targeted:59+counts.targeted},fits:true},null,2)+'\n');
let md='# Frozen full command-to-obligation sheet v1\n\nAuthority: original S4 contract, v2 R1-R18/C1-C26 and all admitted amendments; v3.1 replaces only P01/P07 body sensitivity; current budget v2 replaces all budget figures. All13 admitted files read; no owner receipt credited. Commands below have literal argv; row-level hashes, cwd, world and prerequisites in COMMANDS.json form this same sheet. Plan is independently derived from complete M1R metadata, not predecessor work. Full candidate seven-commit span over3590c001.\n\nCost: '+JSON.stringify(counts)+' including M1-S/M1-T/M1R-T already spent; distinct ceilings12/80 verified. Unallocated capacity is not a coverage bucket or permission to retry. Every additional launch requires explicit versioned row and fresh fit.\n\nDiscovery: all measured3478 declarations including24 Prop candidates and1285 theorem declarations are input observations, never quotas. Full sorted per-identity metadata index planning/M1R-expr-hashes.jsonl is incorporated into this sheet; each declaration binds FinalInventory, final-reconcile, and (if original) BaseInventory/expr-compare. Each theorem additionally binds Axioms; no source-name replacement for measured identities. Any new/removed identity or unknown sort stops dependent reconciliation until explicitly classified; no truncation. Module/artifact ownership is resolved per loaded olean not name prefix.\n\n';
for(const r of rows)md+='## '+r.id+' — '+r.obligation+'\n\nClass/layer: '+r.charge+' / '+r.layer+'. World: '+r.world+'. Prerequisites: '+r.prerequisites.join(', ')+'.\n\nCwd: `'+r.cwd+'`\n\nArgv: `'+JSON.stringify(r.argv)+'`\n\nObservation: '+r.observation+'\n\nOutputs: '+r.outputs.join(', ')+'. Inputs: see full sha256 bindings for this row in COMMANDS.json and global manifest. '+r.stop+'\n\n';
fs.writeFileSync(f+'/COMMAND-SHEET.md',md);console.log(JSON.stringify(counts));
