from pathlib import Path
import hashlib,json
R=Path(__file__).parent
h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
ledger=json.loads((R/'command-ledger.json').read_text());commands=ledger['commands']; by={c['id'].split('-')[0]:c for c in commands}
mutations=[('C1 economic view key','P01'),('C2 integrated initial members','P03'),('C3 economic auth','P04'),('C4 integrated auth','P05'),('economic extra top key','P10'),('integrated extra top key','P11'),('economic extra nested key','P12'),('integrated extra nested key','P13'),('empty traces','P16'),('empty steps','P17'),('same-length trace permutation','P18'),('same-length step permutation','P19'),('economic byte drift','P27'),('integrated byte drift','P28'),('manifest hash drift','P29'),('jq declaration omission','P33'),('CI step deletion','P34'),('CI step no-op bypass','P35'),('pre-repair arity guard absent','P38')]
mutledger=[]
for name,p in mutations:
 c=by[p]; mutledger.append(dict(mutation=name,applied=True,executed=True,killed=True,survivor=False,receipt=p,evidence=c['evidence'],sha256=c['sha256']))
(R/'mutation-ledger.json').write_text(json.dumps({'fault_model':'19 named data/config/source mutations; no global completeness claim','applied':19,'executed':19,'killed':19,'survivors':0,'excluded_attempts':['P26 setup failed before recipe','P31 supplemental axiom query instrument namespace error'],'additional_failure_injections':['P20 missing economic','P21 missing integrated','P22 malformed economic','P23 malformed integrated','P24 second output is directory'],'rows':mutledger},indent=2)+'\n')
rows=[
('I86-A','BLOCKING','PASS (local scope)','P27 P28 P29 P30 P34 P35 P36','Actual committed CI command rejects each corpus drift and real manifest drift; clean path succeeds; deleting step and executing no-op bypass both fail the auditor detector. Remote CI is the ticket owner\'s separate leg, unverified here.'),
('I86-B','BLOCKING','PASS','P33 P32','Exact pre-repair project.nix omission control: clean lookup fails, recipe reaches compiled check then fails at jq with exit 127. Candidate clean shell resolves /nix/store/qvbwz06cqra3cmlra40v0adw75j6j7wm-jq-1.8.1-bin/bin/jq and recipe exits 0.'),
('I86-C1','BLOCKING','PASS','P01 P02 P06 P37','ZZZ mutation rejected for economic view mismatch; same bytes pass shipped key-set program, separating value from shape. Live view independently re-derived from imports.'),
('I86-C2','BLOCKING','PASS','P03 P06 P37','Empty integrated initial members rejected for live corpusInitial mismatch; live initial equals stored initial.'),
('I86-C3','BLOCKING','PASS','P04 P06 P37','Economic permissive auth identity rejected by the compiled context checker; current string equals live identity.'),
('I86-C4','BLOCKING','PASS','P05 P06 P37','Integrated permissive auth identity rejected by the compiled context checker; current string equals live identity.'),
('I86-C-CLAIM','BLOCKING','PASS (claim limit)','P37','Module explicitly disclaims serializer-instance independence. Inspection confirms shared ToJson instances; P37 re-derives the live values, not an independent encoder. This is a documentary bound, not a killed behavioral mutant.'),
('I86-D','BLOCKING','PASS','P07 P08 P09 P38','All three malformed forms exit 1 with identical full directory byte inventories. Exact pre-repair source exits 0 and overwrites both check and a; the no-write detector rejects those effects.'),
('I86-KEYS','BLOCKING','PASS','P10 P11 P12 P13 P14 P15 P39 P40','Both shipped jq programs reject extra keys at the top and one nested level, and reject empty arrays. Positive controls pass. P02 demonstrates context/key-set separability.'),
('I86-ADD','BLOCKING','PASS (Git provenance)','S1 S2','245 protected accepted-base file blobs unchanged. Every prior line preserved in the four modified existing files; new paths confined to exporter, corpus and mandates. All corpus/manifest bytes equal frozen 9c8756a input. No code-mutation claim is made for this Git-metadata row.'),
('I86-E','ADVISORY','PASS (artifact truth)','P37','Handoff f6dd0df4 matches current hashes, 5 traces/32 events/7 steps and zero UNPROVED; historical fed19b3 bytes independently hash to 91526dc6 and contain one UNPROVED. Dated history, vote hole, provisional list, replayer table, and stale-comment route preserved.'),
('G74-CALLS-EXISTING','BLOCKING','PASS','S1 P06 P16 P17 P18 P19 P37','Full leaf exporter reviewed: calls seedCorpus/emitIntegratedCorpus directly, no second event list; empty arrays and same-size permutations rejected against live definitions. Current extents independently re-derived.'),
('G74-VERIFY-FAILS-CLOSED','BLOCKING','PASS','P27 P28 P29 P30','Executed the committed recipe against actual corrupt files and actual corrupt manifest, not the gate\'s untouched-manifest comparison. All fail at the intended checker; clean version passes.')]
lines=['# Commit audit — issue 86, submission 1, replacement seat s86-audit-2','',
'**Verdict: AUDIT-PASS for the enumerated local audit.** No candidate findings. This is not acceptance: real remote CI at the clean final SHA remains the ticket owner\'s separate obligation under R86-A and the owner receipt. It was neither executed nor inferred here.','',
'- Candidate: `38c6d0629c14dfc2209c56450475a77c445fba1f`; parent `6ec3ce315158c4615fcaf0ac9986efc6d3c5f8b3`.',
'- Subject: FULL `4a6cd87..38c6d06`, including all inherited exporter artifacts. `9c8756a` is corpus-input provenance, not the accepted code base.',
'- Seat: fresh codex context, live PID 1301444, pane `%543`, window `reactivegas-e67-t86-exporter-successor`; model `gpt-6-astra`, effort `high`, argv independently inspected. Parent `%529`, author `%531`; no author contact.',
'- Mandate: all six `specs/86-exporter-successor/` hashes match the brief. Diff and provenance retained in `evidence/full.diff`, `evidence/tip.diff`, `evidence/git-provenance.txt`.',
'- Frozen gate: `3579e71cb263d2408657d86ac666a0b85e5c0c44f554932d1e9f21873f627626`. Missing worktree copy restored byte-for-byte from the explicitly named backup; never edited.',
'- Submission remains 1/2; invalid predecessor neither resets cap nor supplies acceptance. Ceiling raises: 0. Historical building audits: 1/3 on entry, 3/3 on exit; this seat used two substantive invocations. Separate ticket counter at dispatch was 3/8; no parent ledger was edited.',
'- All 40 allowed targeted probe invocations used, including two non-candidate instrument/setup failures. No further full gate, cold tree, or backend build was launched. Campaign ended at the fixed probe cap after the enumerated behavioral classes were settled.',
'', '## Invariant ledger','',
'PASS here means the named local observation is supported. Documentary and Git-provenance rows are identified separately and are not relabeled as killed behavioral mutants. Row IDs below link to exact command receipts in `command-ledger.json` and the receipt index in this report.','',
'| Invariant | Severity | Verdict | Receipts | Evidence and limit |','|---|---|---|---|---|']
for row in rows:lines.append('| '+' | '.join(row)+' |')
lines+=['','## Executed verification and accounting','',
'1. S1: `nix develop --quiet -c just ci` from absent `.lake` and `dist-newstyle`, exit 0, 153474 ms. The Cabal library/server compiled; formatting and hlint ran (`No hints`); Lean toolchain 4.25.0 matched; inversion coverage was 14/14, its withheld-backdonate negative control was detected; trace agreement was 14/14; Lean library and exporter built; corpus output matched, both manifest entries passed, compiled check reported 5/32/7.',
'2. S2: exact `nix develop --quiet -c ./gate.sh`, exit 0, 1571 ms, all 11 printed subrow lines passed (the nine named rows include subchecks). Independent execution produced deterministic output equal to the owner\'s log; equality was not used instead of running it.',
'3. P27–P30, P32–P33, P36 each reach the recipe\'s nested `lake build corpusExport`: seven targeted warm/cache-only invocations, each with this seat\'s `.lake` mounted read-only. All report replayed jobs and none report a newly built job. These are explicitly enumerated warm recipe probes under command 3 of the brief, not hidden cold builds. P26 fails before any Lake invocation. P31/P37 use `lake env lean`; P38 uses `lake env bash` then interpreted `lean --run` with existing imports and no backend output.',
'4. Corpus/Git/hash inspection and ledger/report generation are non-compiling records, separately accounted from the 40 executable probes. Source-text inspection closes no behavioral row.',
'', '## Failure modes and controls','',
'- Malformed check arity: pre-repair two-argument fallthrough returned success and wrote both destinations; candidate returns 1 before either write. Full directory inventories establish effects (P07–P09, P38).',
'- Second write failure: deliberately targeting a directory returns 1 while the first file contains the emitted economic bytes. The documented non-atomic limit remains observable (P24); this audit asserts no broader atomicity.',
'- Missing and malformed inputs: economic/integrated missing files propagate IO errors; malformed JSON reports parse failure, all exit 1 (P20–P23). Context mismatches now return explicit errors (P01/P03–P05). No asynchronous, synchronization, or retry path was introduced by the repair.',
'- jq absence: the exact pre-repair declaration fails lookup in the clean shell, passes earlier emission/comparison/check stages, then exits 127 at jq; restored declaration resolves the Nix-store tool and succeeds (P33/P32). The earlier local Python-not-in-PATH setup failure is unrelated and is retained in STATUS.',
'- Ignored-state residue: S1 began with both build trees absent; subsequent corruption probes use only S1 artifacts mounted read-only. Corrupt fixtures remain rejected with the warm artifacts; tracked tree is clean afterward. No owner cache/binary or predecessor instrument supplied an audit result.',
'', '## Mutation ledger and limits','',
'`mutation-ledger.json` enumerates 19 distinct applied data/config/source mutations: 19 executed, 19 killed by the relevant checker/detector, 0 observed survivors within this named set. Empty-array fixtures are reused against both live-value and key-set checks and are counted once per distinct mutant, not twice. Five additional missing/malformed/write-failure injections are reported separately. These totals are finite sampled evidence, not a claim about arbitrary mutants.',
'P26 is a mount-environment setup failure: just attempted its temporary script in a read-only runtime directory, so the recipe did not execute. P27 corrected that private runtime path; its intended cmp failure was observed, although the harness initially expected a different path prefix in the diagnostic. No rerun or extra mutation was charged for correcting that postcheck. P31 evaluated all requested live context values but its supplemental withdrawal axiom query used the wrong namespace; P37 corrected the instrument and passed. Neither setup/import error is a candidate finding or a killed mutant.',
'The arity detector\'s known-defect falsification P38 was executed after the candidate sentinel observations; its late ordering is recorded rather than represented as a RED-before-GREEN chronology. The same saved inventories establish both outcomes; no timing or concurrency claim relies on interpreted code.',
'Key-set mutant probes invoke the host jq; P32 separately executes the exact shipped programs with declared Nix jq. No jq implementation proof is claimed. The view/auth/initial live comparison shares the exporter\'s ToJson instances and identity definitions. Auth execution samples are both false; the source defines the refusing closures. Serializer-instance independence and backdonation coverage are not established.',
'The Lean model/proofs are protected inherited context, not a newly commissioned whole-model proof audit. The supplemental current declaration checks report `step_close_inv` and `Reactivegas.step_withdraw_inv` using only `propext`. No votes are covered by these corpora; the handoff explicitly retains that hole and provisional semantics.',
'', '## Hash-bound artifacts','']
for f in ['command-ledger.json','mutation-ledger.json','instruments.sha256','evidence/reconciliation.json','evidence/content-census.json','evidence/full.diff','evidence/tip.diff','evidence/final-state.txt','evidence/log-review.json']:
 lines.append(f'- `{f}` SHA-256 `{h(R/f)}`.')
lines+=['','## Command receipt index','',
'Exact argv, CWD, scope, nested commands, cache class, exit, duration and full evidence paths are in the hash-bound `command-ledger.json`. The table below provides every command\'s output receipt. Every log is retained in full. The 650911-byte full-CI log was also scanned end-to-end into `evidence/log-review.json`; compiler warnings are not represented as a zero-warning result.','',
'| ID | Exit | ms | Evidence | SHA-256 |','|---|---:|---:|---|---|']
for c in commands:lines.append(f"| {c['id']} | {c['exit']} | {c['duration_ms']} | {Path(c['evidence']).relative_to(R)} | {c['sha256']} |")
lines+=['','## Return boundary','',
'Local report only. No source repair, commit, push, issue/PR comment, external paste, owner contact, merge, or acceptance decision. Final HEAD and gate hash unchanged; tracked worktree clean. The audit worktree and S1 build artifacts remain intact. No rebuilt project exists under the runtime root to retire. Upward delivery is this report and own STATUS only.']
(R/'report.md').write_text('\n'.join(lines)+'\n')
print('report.md bytes=',(R/'report.md').stat().st_size,'sha256=',h(R/'report.md'))
