import fs from 'node:fs';import crypto from 'node:crypto';
const rt='/tmp/reactivegas/ms2/e-lean-compliance/candidate-auditor-s4b-sub2-final-r2',v4=rt+'/instruments/full-v4',v5=rt+'/instruments/full-v5';
const read=p=>fs.readFileSync(p,'utf8'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
if(fs.existsSync(v5))throw Error('version exists');fs.mkdirSync(v5);
fs.writeFileSync(v5+'/run-one.mjs',read(v4+'/run-one.mjs').replaceAll('/instruments/full-v4/','/instruments/full-v5/'));
const setup=`import fs from 'node:fs';import crypto from 'node:crypto';
const rt=${JSON.stringify(rt)},src='/code/reactivegas-66-s4b-audit5/lean/.lake/build/lib/lean',dst=rt+'/worlds/shadow-P07-v5';
const h=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
if(!fs.existsSync(rt+'/instruments/full-v5/ADMISSION.json'))throw Error('not admitted');
if(fs.existsSync(dst))throw Error('overlay must be absent');
const producer=JSON.parse(fs.readFileSync(rt+'/evidence/full-v2/P07-compile.json','utf8'));if(producer.exit!==0)throw Error('missing compiled mutant prerequisite');
const selected='Reactivegas/Step.olean',mut=rt+'/worlds/shadow-P07/'+selected;
const lines=fs.readFileSync(rt+'/evidence/M1/oleans.sha256','utf8').trim().split('\\n').filter(l=>l.slice(66).startsWith('lean/.lake/build/lib/lean/'));
for(const l of lines){const p=l.slice(66+'lean/.lake/build/lib/lean/'.length);if(h(src+'/'+p)!==l.slice(0,64))throw Error('clean dependency drift '+p);}
fs.cpSync(src,dst,{recursive:true});fs.copyFileSync(mut,dst+'/'+selected);
const files=lines.map(l=>{const p=l.slice(66+'lean/.lake/build/lib/lean/'.length),actual=h(dst+'/'+p),expected=p===selected?h(mut):l.slice(0,64);if(actual!==expected)throw Error('overlay drift '+p);return {path:dst+'/'+p,relative:p,sha256:actual,role:p===selected?'one mutant module':'verified clean M1-S dependency'};});
if(h(dst+'/KelGroups/Types.olean')===h(rt+'/worlds/shadow-P01/KelGroups/Types.olean'))throw Error('P01 contamination');
if(h(dst+'/'+selected)===h(src+'/'+selected))throw Error('mutant not installed');
fs.writeFileSync(rt+'/evidence/full-v2/P07-overlay-v5.json',JSON.stringify({utc:new Date().toISOString(),producer:'P07-compile',world:dst,onlyChangedModule:selected,files},null,2)+'\\n');
console.log('P07-OVERLAY verified clean dependencies plus retained mutant Step, no P01 Types');
`;
fs.writeFileSync(v5+'/overlay-prepare.mjs',setup);
const rows=JSON.parse(read(v4+'/COMMANDS.json')),prior=rows.find(r=>r.id==='P07-neg');
prior.actualDisposition='COUNTED AUDITOR SETUP FAILURE: namespace/package root selected partial P07 shadow, then State.olean absent. No inversion failure and no P07 witness from this receipt. P07-pos is a valid prior clean baseline using the exact same driver bytes.';
const r={...prior,id:'P07-negR',argv:prior.argv.map(a=>a.startsWith('LEAN_PATH=')?'LEAN_PATH='+rt+'/worlds/shadow-P07-v5':a),world:rt+'/worlds/shadow-P07-v5; complete independently verified clean M1-S library with ONLY retained mutant Step.olean substituted',prerequisites:['P07-compile','P07-pos'],obligation:'P07 selected original inversion chain and mutant forbidden-close witness, repaired complete isolated package overlay',actualDisposition:undefined,inputs:[...prior.inputs,{path:v5+'/overlay-prepare.mjs',sha256:sha(v5+'/overlay-prepare.mjs')}],outputs:['stdout','stderr','json'].map(e=>rt+'/evidence/full-v2/P07-negR.'+e)};rows.push(r);
const totals={substantive:1,targeted:2};for(const r of rows)totals[r.charge]++;
if(totals.substantive>12||totals.targeted>80)throw Error('full fit exceeded');
fs.writeFileSync(v5+'/COMMANDS.json',JSON.stringify(rows,null,2)+'\n');
fs.writeFileSync(v5+'/FIT.json',JSON.stringify({totalPlanned:totals,ceiling:{substantive:12,targeted:80},headroom:{substantive:12-totals.substantive,targeted:80-totals.targeted},fits:true},null,2)+'\n');
let sheet='# Complete current command-to-obligation sheet v5\n\nOriginal full contract and all amendments remain required. Earlier command results retain their actual charges and scope. S02, Exceptions and P07-neg setup failures remain preserved; no setup diagnostic is a kill. Every measured classification/declaration/witness row from full-v2 remains incorporated by command ID. The valid earlier P07-pos receipt supplies the otherwise-identical positive driver; same driver bytes and clean dependency hashes remain unchanged. P07-negR reuses the already-successful P07-compile output with a NEW complete overlay. This does not close the HISTORICAL P07 isolation limitation. No compiler work occurs in overlay preparation.\n\nSetup argv '+JSON.stringify(['node',v5+'/overlay-prepare.mjs'])+' cwd='+rt+'; frozen script verifies producer exit0, absent destination, every clean dependency digest, sole Step substitution and exclusion of P01 Types. Output evidence/full-v2/P07-overlay-v5.json is required and inspected before P07-negR. All other setup rows remain as full-v2 plus full-v3 S11. Full fit12 substantive/73 targeted within12/80, seven targeted spare; all final cold/CI/inventory/axiom/Expr/panic rows reserved.\n\n';
for(const r of rows)sheet+='## '+r.id+'\n\n'+JSON.stringify(r,null,2)+'\n\n';fs.writeFileSync(v5+'/COMMAND-SHEET.md',sheet);
const files=fs.readdirSync(v5).map(n=>v5+'/'+n).concat([rt+'/instruments/extend-v5.mjs',v4+'/MANIFEST.sha256',rt+'/instruments/full-v2/CLASSIFICATION-ROWS.json',rt+'/instruments/full-v2/DECLARATION-ROWS.jsonl',rt+'/instruments/full-v2/WITNESS-ROWS.json']);
fs.writeFileSync(v5+'/MANIFEST.sha256',files.sort().map(p=>sha(p)+'  '+p.slice(rt.length+1)).join('\n')+'\n');
const manifest=sha(v5+'/MANIFEST.sha256'),utc=new Date().toISOString();fs.writeFileSync(v5+'/ADMISSION.json',JSON.stringify({utc,manifest,totals,authority:'existing12/80; versioned targeted repair'},null,2)+'\n');
fs.appendFileSync(rt+'/STATUS.md',utc+'  PLAN-AMENDMENT  full-v5 manifest='+manifest+'; P07-neg counted missing-State import setup failure, no inversion credit. P07-negR uses new COMPLETE clean M1-S overlay with only retained successful mutant Step substituted, exact dependency hashes/exclusion verified before run; valid prior P07-pos same bytes retained, no extra compile or positive rerun. Full plan12 substantive/73 targeted fits12/80 with all final trust work reserved; historical P07 isolation OPEN.\n');console.log(JSON.stringify({manifest,totals}));
