import fs from 'node:fs';import crypto from 'node:crypto';
const rt='/tmp/reactivegas/ms2/e-lean-compliance/candidate-auditor-s4b-sub2-final-r2',v2=rt+'/instruments/full-v2',v3=rt+'/instruments/full-v3',v4=rt+'/instruments/full-v4';
const read=p=>fs.readFileSync(p,'utf8'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
if(fs.existsSync(v4))throw Error('version exists');fs.mkdirSync(v4);
const original=read(v2+'/Exceptions.lean');let fixes=0;
const repaired=original.split('\n').map(l=>{if(l.startsWith('example :')&&l.includes('authorizedStep')&&l.endsWith(':= by decide')){fixes++;return l.replace(':= by decide',':= by unfold authorizedStep; decide');}return l;}).join('\n');
if(fixes!==28)throw Error('unexpected frozen P11 fixture footprint');
fs.writeFileSync(v4+'/ExceptionsR.lean',repaired);
fs.writeFileSync(v4+'/run-one.mjs',read(v3+'/run-one.mjs').replaceAll('/instruments/full-v3/','/instruments/full-v4/'));
fs.writeFileSync(v4+'/panic-check.mjs',read(v2+'/panic-check.mjs').replace("'Exceptions','P01-pos'","'Exceptions','ExceptionsR','P01-pos'"));
const rows=JSON.parse(read(v3+'/COMMANDS.json')),prior=rows.find(r=>r.id==='Exceptions');
rows.push({...prior,id:'ExceptionsR',argv:prior.argv.map(a=>a===v2+'/Exceptions.lean'?v4+'/ExceptionsR.lean':a),inputs:prior.inputs.map(i=>i.path===v2+'/Exceptions.lean'?{path:v4+'/ExceptionsR.lean',sha256:sha(v4+'/ExceptionsR.lean')}:i),obligation:'Recover Exceptions P11 runtime projection evidence after counted auditor Decidable-instance setup failure; same statements and all R0/V4/Reach observations',outputs:['stdout','stderr','json'].map(e=>rt+'/evidence/full-v2/ExceptionsR.'+e)});
prior.actualDisposition='COUNTED AUDITOR SETUP FAILURE: automatic Decidable synthesis did not unfold authorizedStep for28 P11 concrete examples. All diagnostics preserved; printed markers alone establish no P11 runtime result. Recover with ExceptionsR, same statements and explicit unfolding.';
const panic=rows.find(r=>r.id==='panic-final');panic.argv=panic.argv.map(a=>a===v2+'/panic-check.mjs'?v4+'/panic-check.mjs':a);panic.inputs=panic.inputs.map(i=>i.path===v2+'/panic-check.mjs'?{path:v4+'/panic-check.mjs',sha256:sha(v4+'/panic-check.mjs')}:i);panic.prerequisites.push('ExceptionsR');
const totals={substantive:1,targeted:2};for(const r of rows)totals[r.charge]++;
if(totals.substantive>12||totals.targeted>80)throw Error('full plan no longer fits');
fs.writeFileSync(v4+'/COMMANDS.json',JSON.stringify(rows,null,2)+'\n');
fs.writeFileSync(v4+'/FIT.json',JSON.stringify({totalPlanned:totals,ceiling:{substantive:12,targeted:80},headroom:{substantive:12-totals.substantive,targeted:80-totals.targeted},fits:true},null,2)+'\n');
let sheet='# Complete current command-to-obligation sheet v4\n\nOriginal full mandate and all amendments retained. All command rows below are current; full-v2 classification/declaration/witness and setup rows remain incorporated by command identity. S02 and Exceptions failed setups remain charged and preserved. S11 recovers counterpart detection; ExceptionsR recovers P11 evaluations without changing any assertion statement. The28 existing P11 statements are unfolded to the Bool equality before `decide`; no Decidable oracle or production instance is manufactured. All14 generic rfl projections, R0, V4 and Reach observations are unchanged. Total12 substantive/72 targeted fits12/80 separately; final S09/S10/inventory/axioms/Expr/totality remain reserved. No source repair. Historical limitations OPEN.\n\n';
for(const r of rows)sheet+='## '+r.id+'\n\n'+JSON.stringify(r,null,2)+'\n\n';fs.writeFileSync(v4+'/COMMAND-SHEET.md',sheet);
const files=fs.readdirSync(v4).map(n=>v4+'/'+n).concat([rt+'/instruments/extend-v4.mjs',v3+'/MANIFEST.sha256',v2+'/CLASSIFICATION-ROWS.json',v2+'/DECLARATION-ROWS.jsonl',v2+'/WITNESS-ROWS.json',v2+'/SETUP-COMMANDS.json']);
fs.writeFileSync(v4+'/MANIFEST.sha256',files.sort().map(p=>sha(p)+'  '+p.slice(rt.length+1)).join('\n')+'\n');
const manifest=sha(v4+'/MANIFEST.sha256'),utc=new Date().toISOString();
fs.writeFileSync(v4+'/ADMISSION.json',JSON.stringify({utc,manifest,totals,authority:'existing unchanged12/80; versioned single targeted instrument repair'},null,2)+'\n');
fs.appendFileSync(rt+'/STATUS.md',utc+'  PLAN-AMENDMENT  full-v4 manifest='+manifest+'; Exceptions exit1 counted setup failure automatic Decidable could not unfold authorizedStep; ExceptionsR preserves28 assertion statements with explicit unfold before decide. Full plan12 substantive/72 targeted fits12/80; no other row dropped, all final trust operations reserved; old marker prints not P11 coverage.\n');
console.log(JSON.stringify({manifest,totals}));
